
# Auto deploy to render when merge with main
name: Main Deployment
env: 
  deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

# Sets condition for running deploy
on: 
  pull_request:
    types: closed
    branches:
      - main # Deploy executes with these conditions from main

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: CI and CD using Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: Deploy To Render
        run: curl "$deploy_url" # If configured right, this should send req to deploy hook, and trigger deployment